# Generated by Django 5.2.15 on 2026-07-16 15:03

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('avatar_type', models.CharField(choices=[('initials', 'Initials'), ('google', 'Google Profile'), ('icon', 'Icon')], default='initials', max_length=8)),
                ('avatar_icon', models.CharField(blank=True, max_length=10, null=True)),
                ('can_create_workspace', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('midnight', 'Midnight')], default='light', max_length=16)),
                ('accent_color', models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink'), ('rose', 'Rose'), ('amber', 'Amber'), ('emerald', 'Emerald'), ('cyan', 'Cyan'), ('slate', 'Slate')], default='indigo', max_length=16)),
                ('density_mode', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact'), ('cozy', 'Cozy')], default='comfortable', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
