# Generated by Django 5.0.6 on 2026-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_workspace',
            field=models.BooleanField(default=True),
        ),
    ]
