# Generated by Django 5.0.6 on 2026-06-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_create_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='density_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('midnight', 'Midnight')], default='light', max_length=16)),
                ('accent_color', models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink'), ('rose', 'Rose'), ('amber', 'Amber'), ('emerald', 'Emerald'), ('cyan', 'Cyan'), ('slate', 'Slate')], default='indigo', max_length=16)),
                ('density_mode', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact'), ('cozy', 'Cozy')], default='comfortable', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
