# Generated by Django 5.2.15 on 2026-06-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_type',
            field=models.CharField(choices=[('initials', 'Initials'), ('google', 'Google Profile'), ('icon', 'Icon')], default='initials', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
