# Generated by Django 5.2.15 on 2026-06-20 20:40

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0013_workspacemodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('identifier', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='workspaces.workspacemember')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='organization.department')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_head', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='workspaces.workspacemember')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.jobtitle')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to='workspaces.workspacemember')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingLine',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports', to='workspaces.workspacemember')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_to', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_lines', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('identifier', models.CharField(max_length=6)),
                ('color', models.CharField(default='#8b5cf6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='organization.department')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='workspaces.workspacemember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.team')),
            ],
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['workspace', 'parent'], name='dept_workspace_parent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(fields=['department', 'is_head'], name='deptmember_dept_head_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(fields=['member'], name='deptmember_member_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentmember',
            unique_together={('department', 'member')},
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['workspace', 'level'], name='jobtitle_workspace_level_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='orgprofile',
            index=models.Index(fields=['job_title'], name='orgprofile_jobtitle_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingline',
            index=models.Index(fields=['workspace', 'manager'], name='repline_workspace_manager_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingline',
            unique_together={('workspace', 'report')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['workspace', 'department'], name='team_workspace_dept_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'is_lead'], name='teammember_team_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['member'], name='teammember_member_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member')},
        ),
    ]
