# Generated by Django 5.2.15 on 2026-07-16 15:03

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('identifier', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='workspaces.workspacemember')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='organization.department')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='workspaces.workspacemember')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('bank_iban', models.CharField(blank=True, max_length=64)),
                ('national_id', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('work_location_url', models.URLField(blank=True, max_length=500)),
                ('work_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('work_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bio', models.TextField(blank=True)),
                ('locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.jobtitle')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to='workspaces.workspacemember')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='organization.orgprofile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportingLine',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports', to='workspaces.workspacemember')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_to', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_lines', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('identifier', models.CharField(max_length=6)),
                ('color', models.CharField(default='#8b5cf6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='organization.department')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='workspaces.workspacemember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.team')),
            ],
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['workspace', 'parent'], name='dept_workspace_parent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(fields=['member'], name='deptmember_member_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentmember',
            unique_together={('department', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['profile', 'order'], name='emergcontact_profile_order_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingline',
            index=models.Index(fields=['workspace', 'manager'], name='repline_workspace_manager_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingline',
            unique_together={('workspace', 'report')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['workspace', 'department'], name='team_workspace_dept_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['member'], name='teammember_member_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member')},
        ),
    ]
