# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_departmentmember_deptmember_dept_head_idx_and_more'),
        ('workspaces', '0018_alter_inboxitem_event_type_alter_inboxitem_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to='workspaces.workspacemember'),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
