# Generated by Django 5.2.15 on 2026-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_orgprofile_approved_at_orgprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='work_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='work_location_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='work_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
