# Generated by Django 5.2.15 on 2026-07-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_orgprofile_work_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofile',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='orgprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='orgprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orgprofile',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
