# Generated by Django 5.2.15 on 2026-07-16 15:03

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, db_index=True, max_length=6)),
                ('description', models.TextField(blank=True)),
                ('board_type', models.CharField(choices=[('software', 'Software'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('client', 'Client Project'), ('hr', 'HR & People'), ('design', 'Design'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boards', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('fire_count', models.PositiveIntegerField(default=0)),
                ('trigger', models.JSONField(default=dict)),
                ('conditions', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='projects.board')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BoardField',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('url', 'URL'), ('date', 'Date')], default='text', max_length=20)),
                ('options', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='projects.board')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='projects.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('multiselect', 'Multi-Select'), ('date', 'Date'), ('file', 'File Upload')], default='short_text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='projects.form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.board')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('time_period', models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4'), ('annual', 'Annual'), ('custom', 'Custom')], default='q1', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='projects.board')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objectives', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.objective')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.board')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('lowest', 'Lowest'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], default='medium', max_length=20)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('feature', 'Feature'), ('story', 'Story'), ('epic', 'Epic'), ('improvement', 'Improvement'), ('question', 'Question')], default='task', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimate_points', models.PositiveIntegerField(blank=True, null=True)),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='projects.label')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.task')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='projects.objective')),
                ('tasks', models.ManyToManyField(blank=True, related_name='key_results', to='projects.task')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('closed', 'Closed')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.form')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_submission', to='projects.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('override_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_overrides', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.task')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='projects.taskcomment')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('blocks', 'Blocks'), ('blocked_by', 'Blocked by'), ('relates_to', 'Relates to'), ('duplicate_of', 'Duplicate of'), ('cloned_from', 'Cloned from')], default='blocks', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_deps', to='projects.task')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_deps', to='projects.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFieldValue',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.boardfield')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='projects.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('is_started', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projects.board')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.taskstatus'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('feature', 'Feature'), ('story', 'Story'), ('epic', 'Epic'), ('improvement', 'Improvement'), ('question', 'Question')], default='task', max_length=20)),
                ('priority', models.CharField(choices=[('lowest', 'Lowest'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], default='medium', max_length=20)),
                ('default_subtasks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='projects.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('task', 'Task'), ('board', 'Board')], max_length=20)),
                ('resource_id', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='projects.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wiki_pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.wikipage')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WikiRevision',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.wikipage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalReviewer',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='projects.approval')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reviewed_at'],
                'unique_together': {('approval', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_board_members', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='projects.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('board', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('is_workspace_scoped', models.BooleanField(default=False)),
                ('alert_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='projects.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('board', 'user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('trigger_payload', models.JSONField(default=dict)),
                ('actions_run', models.JSONField(default=list)),
                ('exec_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.automationrule')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='projects.task')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['rule', 'exec_status'], name='automlog_rule_status_idx'), models.Index(fields=['rule', 'created_at'], name='automlog_rule_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('created', 'created the task'), ('updated', 'updated the task'), ('status_changed', 'changed status'), ('priority_changed', 'changed priority'), ('assigned', 'assigned the task'), ('commented', 'added a comment'), ('subtask_added', 'added a subtask')], max_length=30)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.task')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='taskact_task_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='comment_task_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'user', 'emoji')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AlterUniqueTogether(
            name='taskfieldvalue',
            unique_together={('task', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('board', 'name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'status', 'order'], name='task_board_status_order_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'assignee'], name='task_board_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'priority'], name='task_board_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'sprint'], name='task_board_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='task_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'due_date'], name='task_board_due_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplate',
            unique_together={('board', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userpresence',
            unique_together={('user', 'workspace', 'resource_type', 'resource_id')},
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('board', 'slug')},
        ),
    ]
