# Generated by Django 5.2.15 on 2026-06-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_options_remove_task_task_board_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('lowest', 'Lowest'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='priority',
            field=models.CharField(choices=[('lowest', 'Lowest'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], default='medium', max_length=20),
        ),
    ]
