# Generated by Django 5.2.15 on 2026-07-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_approval_overridden_by_approval_override_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditEvent',
        ),
    ]
