# Generated by Django 5.0.6 on 2026-06-03 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_automationrule_automationlog_document_form_formfield_and_more'),
        ('workspaces', '0005_onboardingstate_dismissed_by_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='alert_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedview',
            name='is_workspace_scoped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('widgets', models.JSONField(default=list)),
                ('is_builtin', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
