# Generated by Django 5.0.6 on 2026-06-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_v3_8_0_okr_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyresult',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='history',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='metric_type',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='start_value',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='unit',
        ),
    ]
