# Generated by Django 5.2.15 on 2026-07-16 15:03

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleChatIntegration',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.CharField(max_length=1024)),
                ('space_name', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_chat_integration', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsIntegration',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.CharField(max_length=1024)),
                ('space_name', models.CharField(default='JCN', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams_integration', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationChannelMapping',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('teams', 'Microsoft Teams'), ('google_chat', 'Google Chat')], max_length=20)),
                ('channel_name', models.CharField(blank=True, max_length=128)),
                ('webhook_url', models.CharField(blank=True, max_length=1024)),
                ('notification_format', models.CharField(choices=[('compact', 'Compact'), ('detailed', 'Detailed')], default='detailed', max_length=10)),
                ('enabled_events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_mappings', to='projects.board')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_mappings', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'board', 'platform')},
            },
        ),
    ]
