# Generated by Django 5.2.15 on 2026-07-16 15:03

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workspace_logos/')),
                ('country', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1024)),
                ('events', models.JSONField(default=list)),
                ('secret', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_completed', models.BooleanField(default=False)),
                ('module_ui_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('app_access', models.JSONField(default=dict)),
                ('permissions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-is_system', 'name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAPIKey',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=12)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('request_body', models.TextField()),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='workspaces.webhook')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['webhook', 'created_at'], name='webhookdel_webhook_created_idx'), models.Index(fields=['webhook', 'success'], name='webhookdel_webhook_success_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('verb', models.CharField(max_length=50)),
                ('event_type', models.CharField(default='assigned', max_length=20)),
                ('app', models.CharField(blank=True, max_length=30)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('board_id', models.CharField(blank=True, max_length=100)),
                ('board_name', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived'), ('snoozed', 'Snoozed')], default='unread', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='inbox_user_status_idx'), models.Index(fields=['user', 'workspace', 'status'], name='inbox_user_ws_status_idx'), models.Index(fields=['user', 'workspace', 'app', 'status'], name='inbox_user_ws_app_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('jira', 'Jira'), ('clickup', 'ClickUp'), ('monday', 'Monday'), ('notion', 'Notion'), ('github', 'GitHub Issues'), ('asana', 'Asana'), ('csv', 'Simple CSV')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('mapped', 'Mapping Ready'), ('importing', 'Importing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('parsed_rows', models.JSONField(default=list)),
                ('field_mapping', models.JSONField(default=dict)),
                ('preview_rows', models.JSONField(default=list)),
                ('progress_pct', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('imported_task_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='importjob_workspace_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=100)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='ae_workspace_created_idx'), models.Index(fields=['workspace', 'resource_type'], name='ae_workspace_restype_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Viewer', 'Viewer')], default='Member', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='wsinvite_workspace_status_idx')],
                'unique_together': {('workspace', 'email')},
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspaces.customrole')),
                ('workspace_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignment', to='workspaces.workspacemember')),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='rla_role_idx')],
            },
        ),
    ]
