# Generated by Django 5.0.6 on 2026-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'assigned you a task'), ('task_commented', 'commented on your task'), ('task_mentioned', 'mentioned you in a comment')], max_length=30),
        ),
    ]
