# Generated by Django 5.0.6 on 2026-06-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_notification_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_completed', models.BooleanField(default=False)),
                ('team_type', models.CharField(blank=True, max_length=50)),
                ('checklist_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='workspaces.workspace')),
            ],
        ),
    ]
