# Generated by Django 5.0.6 on 2026-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_onboardingstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingstate',
            name='dismissed_by_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
