# Generated by Django 5.0.6 on 2026-06-04 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_onboardingstate_dismissed_by_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'assigned you a task'), ('task_commented', 'commented on your task'), ('task_mentioned', 'mentioned you in a comment'), ('approval_requested', 'requested your approval')], max_length=30),
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('verb', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('mentioned', 'Mentioned'), ('commented', 'Commented'), ('approved', 'Approval'), ('automated', 'Automated')], default='assigned', max_length=20)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('project_id', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived'), ('snoozed', 'Snoozed')], default='unread', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_item', to='workspaces.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('mentioned', 'Mentioned'), ('commented', 'Commented'), ('approved', 'Approval'), ('automated', 'Automated')], max_length=20)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.CharField(choices=[('instant', 'Instant'), ('digest', 'Digest'), ('off', 'Off')], default='instant', max_length=20)),
                ('project_id_override', models.CharField(blank=True, max_length=100)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('digest_hour', models.PositiveSmallIntegerField(default=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('user', 'workspace', 'event_type', 'project_id_override')},
            },
        ),
    ]
