# Generated by Django 5.0.6 on 2026-06-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_importjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
