# Generated by Django 5.0.6 on 2026-06-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_alter_importjob_options_alter_inboxitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxitem',
            name='notification',
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'assigned you a task'), ('task_commented', 'commented on your task'), ('task_mentioned', 'mentioned you in a comment'), ('approval_requested', 'requested your approval')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
