# Generated by Django 5.2.15 on 2026-06-20 20:40

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_rename_project_id_inboxitem_board_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceModule',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_modules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'is_enabled'], name='wsmodule_workspace_enabled_idx')],
                'unique_together': {('workspace', 'module_key')},
            },
        ),
    ]
