# Generated by Django 5.2.15 on 2026-06-22 10:03

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_workspacemodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='workspacemember',
            name='wsmember_workspace_role_idx',
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='role',
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Viewer', 'Viewer')], default='Member', max_length=20),
        ),
        migrations.AddField(
            model_name='customrole',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workspaces.customrole'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='workspace_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignment', to='workspaces.workspacemember'),
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role'], name='rla_role_idx'),
        ),
    ]
