# Generated by Django 5.2.15 on 2026-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_customrole_roleassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingstate',
            name='checklist_dismissed',
        ),
        migrations.RemoveField(
            model_name='onboardingstate',
            name='dismissed_by_users',
        ),
        migrations.AddField(
            model_name='customrole',
            name='app_access',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='onboardingstate',
            name='module_dismissed_by_users',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
