# Generated by Django 5.2.15 on 2026-06-25 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_remove_onboardingstate_checklist_dismissed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspaces.customrole'),
        ),
    ]
