# Generated by Django 5.2.15 on 2026-06-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_alter_roleassignment_role_cascade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceModule',
        ),
    ]
