# Generated by Django 5.2.15 on 2026-07-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_delete_workspacemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('mentioned', 'Mentioned'), ('commented', 'Commented'), ('approved', 'Approval'), ('automated', 'Automated'), ('org', 'Org')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'assigned you a task'), ('task_commented', 'commented on your task'), ('task_mentioned', 'mentioned you in a comment'), ('approval_requested', 'requested your approval'), ('org_profile_submitted', 'submitted their org profile'), ('org_profile_approved', 'approved your org profile')], max_length=50),
        ),
    ]
