# Generated by Django 5.2.15 on 2026-07-04 11:51

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_alter_inboxitem_event_type_alter_inboxitem_verb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='project_name',
            new_name='board_name',
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='event_type',
            field=models.CharField(default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='verb',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=100)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='ae_workspace_created_idx'), models.Index(fields=['workspace', 'resource_type'], name='ae_workspace_restype_idx')],
            },
        ),
    ]
