# Generated by Django 5.2.15 on 2026-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_rename_project_name_inboxitem_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
