# Generated by Django 5.2.15 on 2026-07-05 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0020_workspacemember_deactivated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='app',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['user', 'workspace', 'app', 'status'], name='inbox_user_ws_app_status_idx'),
        ),
    ]
