# Generated by Django 5.2.15 on 2026-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0021_inboxitem_app_inboxitem_inbox_user_ws_app_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
