# Generated by Django 5.2.15 on 2026-07-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0022_workspace_country_workspace_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboardingstate',
            old_name='module_dismissed_by_users',
            new_name='module_ui_state',
        ),
        migrations.RemoveField(
            model_name='onboardingstate',
            name='team_type',
        ),
    ]
