
export const TOUR_REGISTRY = {
  projects: {
    appLabel: "Project Management",
    landingPath: "boards",
    welcome: {
      title: "Welcome to Project Management 👋",
      body: "A 5-minute walkthrough to help you get started — boards, tasks, notifications, and the shortcuts that make it all fast.",
    },
    steps: [
      {
        key: "create_board_prompt",
        group: "create_board",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="create_board"]',
        watchFor: '[data-tour="board_name_input"]',
        title: "Create your first board",
        body: "Boards organise your work into projects. Try it — click New Board to open the form.",
      },
      {
        key: "board_type_picker",
        group: "create_board",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="board_type_picker"]',
        title: "Pick a type",
        body: "Choose whatever fits best — it sets the board's icon and color.",
      },
      {
        key: "board_name_input",
        group: "create_board",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="board_name_input"]',
        requiresValue: true,
        title: "Name it",
        body: "Give your board a name — that's the only required field.",
      },
      {
        key: "board_private_toggle",
        group: "create_board",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="board_private_toggle"]',
        title: "Public or private",
        body: "Make it private to restrict it to invited members only.",
      },
      {
        key: "board_submit",
        group: "create_board",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="board_submit"]',
        title: "Create it",
        body: "Click Create board to finish — you can add a task right after.",
      },
      {
        // Opens whichever board exists (ctx.boardId) — skipped if none yet.
        key: "add_task_prompt",
        group: "add_task",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="add_task"]',
        watchFor: '[data-tour="task_title_input"]',
        title: "Add a task",
        body: "Break work into trackable pieces. Try it — click Add Task to open the form.",
      },
      {
        key: "task_title_input",
        group: "add_task",
        requiresBoard: true,
        requiresValue: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="task_title_input"]',
        title: "Give it a title",
        body: "That's the only required field.",
      },
      {
        key: "task_optional_fields",
        group: "add_task",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="task_optional_fields"]',
        title: "Everything else is optional",
        body: "Description, status, priority, assignee, and due date — you can fill these in now or leave them for later.",
      },
      {
        key: "task_submit",
        group: "add_task",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="task_submit"]',
        title: "Create it",
        body: "Click Create Task to finish.",
      },
      {
        key: "board_members_prompt",
        group: "board_members",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="board_members"]',
        // watchFor: '[data-tour="board_access_private_toggle"]',
        disableActiveInteraction: true,
        title: "Board members & access",
        body: "You can invite workspace members to this board and control what they can do. and can make the board private to restrict it to invited members only.",
      },
      // {
      //   key: "board_access_private_toggle",
      //   group: "board_members",
      //   requiresBoard: true,
      //   route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
      //   anchor: '[data-tour="board_access_private_toggle"]',
      //   watchFor: '[data-tour="board_add_members"]',
      //   title: "Make it private",
      //   body: "Flip this to restrict the board to only the members listed below.",
      // },
      // {
      //   key: "board_add_members_prompt",
      //   group: "board_members",
      //   requiresBoard: true,
      //   route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
      //   anchor: '[data-tour="board_add_members"]',
      //   // watchFor: '[data-tour="board_member_search"]',
      //   title: "Invite members",
      //   body: "Click Add members to bring workspace members onto this board.",
      // },
      // {
      //   key: "board_member_search",
      //   group: "board_members",
      //   requiresBoard: true,
      //   route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
      //   anchor: '[data-tour="board_member_search"]',
      //   title: "Find and add",
      //   body: "Search, select, pick a role, then click Add.",
      // },
      {
        key: "board_settings_prompt",
        group: "board_settings",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="board_settings"]',
        watchFor: '[data-tour="board_statuses_list"]',
        title: "Board settings",
        body: "Try it — click here to manage this board's columns.",
      },
      {
        key: "board_statuses_list",
        group: "board_settings",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="board_statuses_list"]',
        title: "Your columns",
        body: "Drag to reorder. Mark one Started and one Done to drive task dates and completion %.",
      },
      {
        key: "board_add_status",
        group: "board_settings",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="board_add_status"]',
        disableActiveInteraction: true,
        title: "Add a column",
        body: "Add as many columns as your workflow needs.",
      },
      {
        key: "board_settings_save",
        group: "board_settings",
        requiresBoard: true,
        route: (ws, ctx) => `/w/${ws}/boards/${ctx?.boardId}`,
        anchor: '[data-tour="board_settings_save"]',
        title: "Save changes",
        body: "Nothing changes until you click Save.",
      },
      // {
      //   key: "my_work",
      //   route: (ws) => `/w/${ws}/boards`,
      //   anchor: '[data-tour="nav_my-work"]',
      //   title: "Track what's yours",
      //   body: "My Work rolls up everything assigned to you across every board in this app — your personal to-do list.",
      // },
      {
        key: "sidebar_toggle_prompt",
        group: "notifications",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="sidebar_toggle"]',
        // skipIfPresent: '[data-tour="notification_bell"]',
        watchFor: '[data-tour="notification_bell"]',
        title: "Expand the sidebar",
        body: "Try it — press Ctrl+. (⌘+. on Mac) to expand the sidebar. That's where your notifications live.",
      },
      // {
      //   key: "notifications_prompt",
      //   group: "notifications",
      //   route: (ws) => `/w/${ws}/boards`,
      //   anchor: '[data-tour="notification_bell"]',
      //   watchFor: '[data-tour="notification_panel"]',
      //   title: "Notifications",
      //   body: "Try it — press g then i to open your notifications.",
      // },
      // {
      //   key: "notifications",
      //   group: "notifications",
      //   route: (ws) => `/w/${ws}/boards`,
      //   anchor: '[data-tour="notification_panel"]',
      //   title: "Stay in the loop",
      //   body: "Mentions, assignments, approvals — they all land here.",
      // },
      {
        key: "shortcuts_prompt",
        group: "shortcuts",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="shortcuts_prompt"]',
        watchFor: '[data-tour="shortcuts_overlay"]',
        title: "Keyboard shortcuts",
        body: "This app is fully keyboard-driven. Try it — press ? now to see the full list.",
      },
      {
        key: "shortcuts_overlay",
        group: "shortcuts",
        route: (ws) => `/w/${ws}/boards`,
        anchor: '[data-tour="shortcuts_overlay"]',
        disableActiveInteraction: true,
        title: "Always at your fingertips",
        body: "Press Esc to close this anytime, and ? to bring it back.",
      },
    ],
  },

  people: {
    appLabel: "People & HR",
    landingPath: "hr",
    welcome: {
      title: "Welcome to People & HR 👋",
      body: "A 1-minute walkthrough — org structure, leave, attendance, and the shortcuts that make it all fast.",
    },
    // Note: `set_reporting_line` is shown in the checklist but omitted here — it's changed from an employee's profile (no single, always-present control to spotlight; see MemberDetailPage's read-only "Reports to").
    steps: [
      {
        key: "create_department",
        route: (ws) => `/w/${ws}/departments`,
        anchor: '[data-tour="create_department"]',
        title: "Create a department",
        body: "Departments are the top level of your org structure. Create one to continue.",
      },
      {
        key: "create_team",
        route: (ws) => `/w/${ws}/teams`,
        anchor: '[data-tour="create_team"]',
        title: "Create a team",
        body: "Teams group people within departments. Create your first team to continue.",
      },
      {
        key: "org_directory",
        route: (ws) => `/w/${ws}/people`,
        anchor: '[data-tour="nav_people"]',
        title: "Employee Hub",
        body: "Browse your org chart and team directory, and open anyone's profile from here.",
      },
      {
        key: "submit_leave_request",
        route: (ws) => `/w/${ws}/hr/leave`,
        anchor: '[data-tour="submit_leave_request"]',
        title: "Request leave",
        body: "This is how anyone books time off. Submit a request to see the flow.",
      },
      {
        key: "leave_policies_tab",
        group: "leave_policy",
        route: (ws) => `/w/${ws}/hr/leave`,
        anchor: '[data-tour="leave_policies_tab"]',
        watchFor: '[data-tour="create_leave_policy"]',
        title: "Leave policies",
        body: "Click the Policies tab to define how much annual, sick, and other leave your team gets.",
      },
      {
        key: "create_leave_policy",
        group: "leave_policy",
        route: (ws) => `/w/${ws}/hr/leave`,
        anchor: '[data-tour="create_leave_policy"]',
        title: "Create a policy",
        body: "Set accrual rules and carry-over here, then assign the policy to employees.",
      },
      {
        key: "record_attendance",
        route: (ws) => `/w/${ws}/hr/attendance`,
        anchor: '[data-tour="record_attendance"]',
        title: "Record attendance",
        body: "Clock in to log attendance for the day.",
      },
      {
        key: "hr_overview",
        route: (ws) => `/w/${ws}/hr`,
        anchor: '[data-tour="hr_overview"]',
        title: "Your overview",
        body: "Home rolls up your own leave balance, clock-in status, and team activity in one place.",
      },
      {
        key: "sidebar_toggle_prompt",
        group: "notifications",
        route: (ws) => `/w/${ws}/hr`,
        anchor: '[data-tour="sidebar_toggle"]',
        // Bell only mounts once the sidebar is expanded — nothing to do here if it already is.
        // skipIfPresent: '[data-tour="notification_bell"]',
        watchFor: '[data-tour="notification_bell"]',
        title: "Expand the sidebar",
        body: "Try it — press Ctrl+. (⌘+. on Mac) to expand the sidebar. That's where your notifications live.",
      },
      // {
      //   key: "notifications_prompt",
      //   group: "notifications",
      //   route: (ws) => `/w/${ws}/hr`,
      //   anchor: '[data-tour="notification_bell"]',
      //   watchFor: '[data-tour="notification_panel"]',
      //   title: "Notifications",
      //   body: "Try it — press g then i to open your notifications.",
      // },
      // {
      //   key: "notifications",
      //   group: "notifications",
      //   route: (ws) => `/w/${ws}/hr`,
      //   anchor: '[data-tour="notification_panel"]',
      //   title: "Stay in the loop",
      //   body: "Approvals, mentions, leave updates — they all land here.",
      // },
      {
        key: "shortcuts_prompt",
        group: "shortcuts",
        route: (ws) => `/w/${ws}/hr`,
        anchor: '[data-tour="shortcuts_prompt"]',
        watchFor: '[data-tour="shortcuts_overlay"]',
        title: "Keyboard shortcuts",
        body: "This app is fully keyboard-driven. Try it — press ? now to see the full list.",
      },
      {
        key: "shortcuts_overlay",
        group: "shortcuts",
        route: (ws) => `/w/${ws}/hr`,
        anchor: '[data-tour="shortcuts_overlay"]',
        title: "Always at your fingertips",
        body: "Press Esc to close this anytime, and ? to bring it back.",
      },
    ],
  },
};
